version: '3'

services:

  herbie:
    container_name: 'herbie'
    build: .
    volumes:
      - './src:/data/www'
      - 'static_volume:/data/www/herbie/static'
    depends_on:
      - 'herbie-db'
    environment:
      - 'DATABASE_URL=postgres://user:password@herbie-db:5432/herbie_db'
      - 'SECRET_KEY=thisisasecret'
      - 'GCLOUD_PUBSUB_PROJECT_ID=herbie-app'
      - 'PUBSUB_EMULATOR_HOST=herbie-google-pub-sub:8085'
      - 'AWS_ACCESS_KEY_ID=x'
      - 'AWS_SECRET_ACCESS_KEY=x'
      - 'AWS_SQS_SNS_REGION=local'
      - 'AWS_SQS_SNS_ENDPOINT_URL=http://herbie-aws-sns-sqs:4100'
    ports:
      - '80'
    networks:
      - 'herbie-network'

  herbie-nginx:
    image: 'nginx:latest'
    container_name: 'herbie-nginx'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - 'static_volume:/data/www/herbie/static'
    depends_on:
      - 'herbie-db'
      - 'herbie'
    ports:
      - '${NGINX_PORT}:80'
    networks:
      - 'herbie-network'

  herbie-db:
    container_name: 'herbie-db'
    image: 'postgres:11.5'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=herbie_db'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - 'herbie-network'

  herbie-google-pub-sub:
    container_name: 'herbie-google-pub-sub'
    image: 'knarz/pubsub-emulator'
    ports:
      - '8085:8085'
    networks:
      - 'herbie-network'

  herbie-aws-sns-sqs:
    container_name: 'herbie-aws-sns-sqs'
    image: 'pafortin/goaws'
    ports:
      - '4100:4100'
    networks:
      - 'herbie-network'

volumes:
  db-data:
    driver: 'local'
  static_volume:

networks:
  herbie-network:
    driver: 'bridge'
