version: '3'

services:

  herbie-app:
    container_name: 'herbie-app'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/data/www'
    depends_on:
      - 'herbie-db'
      - 'herbie-google-pubsub'
    environment:
      - 'DATABASE_URL=postgres://user:password@herbie-db:5432/herbie_db'
      - 'SECRET_KEY=thisisasecret'
      - 'GCLOUD_PUBSUB_PROJECT_ID=herbie-app'
      - 'PUBSUB_EMULATOR_HOST=herbie-google-pubsub:8085'
    ports:
      - '8000:8000'
    networks:
      - 'herbie-network'

  herbie-db:
    container_name: 'herbie-db'
    image: 'postgres:11.5'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=herbie_db'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5433:5432'
    networks:
      - 'herbie-network'

  herbie-google-pubsub:
    container_name: 'herbie-google-pubsub'
    image: 'knarz/pubsub-emulator'
    ports:
      - '8085:8085'
    networks:
      - 'herbie-network'

volumes:
  db-data:
    driver: 'local'

networks:
  herbie-network:
    driver: 'bridge'
