version: '3'

services:

  herbie:
    container_name: 'herbie'
    build: .
    volumes:
      - './src:/data/www'
    depends_on:
      - 'herbie-db'
    environment:
      - 'DATABASE_URL=postgres://user:password@herbie-db:5432/herbie_db'
      - 'SECRET_KEY=thisisasecret'
    ports:
      - '8000'
    networks:
      - 'herbie-network'

  herbie-nginx:
    image: 'nginx:1.17'
    container_name: 'herbie-nginx'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - 'herbie-db'
      - 'herbie'
    ports:
      - "80:80"
    networks:
      - 'herbie-network'

  herbie-db:
    container_name: 'herbie-db'
    image: 'postgres:11.5'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=herbie_db'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5433:5432'
    networks:
      - 'herbie-network'

volumes:
  db-data:
    driver: 'local'

networks:
  herbie-network:
    driver: 'bridge'
